
format = """
$username\
$directory\
$git_branch\
$git_tag\
$git_commit\
$git_state\
$git_status\
$custom\
$status
$character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 100

add_newline = false

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) [in](blue bold) "
disabled = false
show_always = true

[directory]
truncation_length = 3
truncate_to_repo = true
style = "yellow bold"

[git_branch]
always_show_remote = true

[git_commit]
commit_hash_length = 6

[git_status]
ahead = "?${count}"
diverged = "??${ahead_count}?${behind_count}"
behind = "?${count}"

[character] 
success_symbol = "[:;](bold green)" 

[kubernetes]
format = '[⛵ $context \($namespace\)](dimmed green) '
disabled = true

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[kubernetes.user_aliases]
"dev.local.cluster.k8s" = "dev"
"*databeamer-test*" = "dbeamr-test"
